# Use container-based environment for quicker initialization
sudo: false

# Since we still support CentOS 6 we need to be able to test 5.3.3
dist: precise

# Specify the build matrix
language: php
php:
    - '5.3.3'
    - '5.4'
    - '7.0'
    - '7.1.6'
env:
    global:
        - NODE_VERSION=6
        - XDMOD_TEST_ARTIFACTS_MIRROR="$HOME/xdmod-test-artifacts.git"
    matrix:
        - TEST_SUITE=syntax
        - TEST_SUITE=style
        - TEST_SUITE=unit
        - TEST_SUITE=build
matrix:
    exclude:
        - php: '5.4'
          env: TEST_SUITE=style

# Add dependency directories to the Travis cache
cache:
    directories:
        - $HOME/.npm
        - $HOME/.composer/cache
        - /tmp/pear/cache
        - $XDMOD_TEST_ARTIFACTS_MIRROR

# Delegate the installation step to the custom Travis installation script
install: ./.travis.install.sh

# Delegate the build step to the custom Travis build script
script: ./.travis.build.sh
