# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open XDMoD
email: ccr-xdmod-help@buffalo.edu
description: >
  XDMoD (XD Metrics on Demand) is an NSF-funded open source tool designed
  to audit and facilitate the utilization of the XSEDE cyberinfrastructure
  by providing a wide range of metrics on XSEDE resources, including
  resource utilization, resource performance, and impact on scholarship
  and research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://open.xdmod.org" # the base hostname & protocol for your site
github_username: ubccr
github_url: https://github.com/ubccr/xdmod
latest_version: "7.0"
version_list:
    - "7.0"
    - "6.6"
    - "6.5"

defaults:
    -
        scope:
            path: "7.0"
            type: "pages"
        values:
            layout: "page"
            version: "7.0"
            menu_markdown: "7.0/menu.md"
    -
        scope:
            path: "6.6"
            type: "pages"
        values:
            layout: "page"
            version: "6.6"
            menu_markdown: "6.6/menu.md"
    -
        scope:
            path: "6.5"
            type: "pages"
        values:
            layout: "page"
            version: "6.5"
            menu_markdown: "6.5/menu.md"

# Build settings
markdown: kramdown
theme_subdir: "/xdmod-jekyll-theme"
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
